# fly.toml app configuration file generated for server-hidden-sunset-5071 on 2024-08-29T13:30:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-hidden-sunset-5071'
primary_region = 'atl'

[build]

[env]
  MONGODB_URI = 'mongodb+srv://duongricher:eZlCF1jMGsA5TlmD@cluster0.chxkcbd.mongodb.net/?retryWrites=true&w=majority'
  PORT = 8080

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
